sudo: required
language: bash

services:
  - docker

before_install:
  - make clean

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  
script:
  - go env
  - go version
  - make all
