sudo: required
language: bash

services:
  - docker

before_install:
  - make clean

script:
  - go env
  - go version
  - mkdir -p /home/travis/gopath/src/github.com/servicebroker
  - ln -s $PWD /home/travis/gopath/src/github.com/servicebroker/servicebroker
  - make all
